import AIBConfig
import Foundation

/// GCP Cloud Run deployment provider.
/// Consolidates all Cloud Run-specific logic: preflight checks, URL resolution,
/// config generation, and deployment commands.
public struct GCPCloudRunProvider: DeploymentProvider, Sendable {

    /// Environment variable names reserved by Cloud Run (auto-set by the system).
    private static let reservedCloudRunEnvKeys: Set<String> = [
        "PORT", "K_SERVICE", "K_REVISION", "K_CONFIGURATION",
    ]
    private var reservedCloudRunEnvKeys: Set<String> { Self.reservedCloudRunEnvKeys }

    public var providerID: String { "gcp-cloudrun" }
    public var displayName: String { "Google Cloud Run" }

    public init() {}

    // MARK: - Preflight

    public func preflightCheckers() -> [any PreflightChecker] {
        [
            BuildBackendAvailabilityChecker(),
            GCloudInstalledChecker(),
            GCloudAuthenticatedChecker(),
            GCloudProjectChecker(),
            CloudRunAPIChecker(),
        ]
    }

    public func preflightDependencies() -> [PreflightCheckID: [PreflightCheckID]] {
        [
            .gcloudInstalled: [.gcloudAuthenticated, .gcloudProjectConfigured, .cloudRunAPIEnabled],
        ]
    }

    // MARK: - Config Detection & Validation

    public func extractDetectedConfig(from report: PreflightReport) -> [String: String] {
        var detected: [String: String] = [:]
        if let project = report.detail(for: .gcloudProjectConfigured), !project.isEmpty {
            detected["gcpProject"] = project
        }
        return detected
    }

    public func validateTargetConfig(_ config: AIBDeployTargetConfig) throws {
        guard let gcpProject = config.providerConfig["gcpProject"], !gcpProject.isEmpty else {
            throw AIBDeployError(
                phase: "config",
                message: "GCP project is required. Set it in .aib/targets/gcp-cloudrun.yaml or ensure gcloud is configured."
            )
        }
    }

    // MARK: - Service Naming

    /// Sanitize a package-derived service name into a valid Cloud Run service name.
    /// Cloud Run names: lowercase letters, hyphens, max 63 chars.
    /// Example: "MyService" -> "myservice"
    public func deployedServiceName(from namespacedID: String) -> String {
        let sanitized = namespacedID
            .replacingOccurrences(of: "/", with: "-")
            .lowercased()
            .filter { $0.isLetter || $0.isNumber || $0 == "-" }

        let trimmed: String
        if let first = sanitized.first, first.isLetter {
            trimmed = sanitized
        } else {
            trimmed = "svc-" + sanitized
        }

        return String(trimmed.prefix(63))
    }

    // MARK: - URL Resolution

    /// Resolve a service_ref to a Cloud Run URL.
    /// Uses the live URL of an already-deployed service when available,
    /// otherwise falls back to the deterministic form.
    public func resolveURL(
        serviceRef: String,
        region: String,
        path: String?,
        serviceNameMap: [String: String],
        existingServiceURLs: [String: String]
    ) -> String {
        let basePath = path ?? "/mcp"
        // Prefer the live URL from an already-deployed service
        if let liveBaseURL = existingServiceURLs[serviceRef] {
            return liveBaseURL + basePath
        }
        let cloudRunName = serviceNameMap[serviceRef] ?? deployedServiceName(from: serviceRef)
        return "https://\(cloudRunName)-\(region).a.run.app\(basePath)"
    }

    // MARK: - Deploy Config Generation

    /// Generate clouddeploy.yaml content for a Cloud Run service.
    public func generateDeployConfig(service: AIBDeployServicePlan) -> String {
        var lines: [String] = []
        lines.append("# Generated by AIB — do not edit manually")
        lines.append("service: \(service.deployedServiceName)")
        lines.append("region: \(service.region)")
        lines.append("resources:")
        lines.append("  memory: \(service.resourceConfig.memory)")
        lines.append("  cpu: \(service.resourceConfig.cpu)")
        lines.append("scaling:")
        lines.append("  max_instances: \(service.resourceConfig.maxInstances)")
        lines.append("  min_instances: 0")
        lines.append("  concurrency: \(service.resourceConfig.concurrency)")
        lines.append("timeout: \(service.resourceConfig.timeout)")
        lines.append("auth: \(service.isPublic ? "public" : "private")")

        let planEnvVars = service.envVars.filter { !reservedCloudRunEnvKeys.contains($0.key) }
        if !planEnvVars.isEmpty {
            lines.append("env:")
            for (key, value) in planEnvVars.sorted(by: { $0.key < $1.key }) {
                lines.append("  \(key): \"\(value)\"")
            }
        }

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Container Registry

    public func registryImageTag(
        service: AIBDeployServicePlan,
        targetConfig: AIBDeployTargetConfig
    ) -> String {
        let gcpProject = requiredGCPProject(from: targetConfig)
        let host = targetConfig.providerConfig["artifactRegistryHost"]
            ?? "\(targetConfig.region)-docker.pkg.dev"
        return "\(host)/\(gcpProject)/\(service.deployedServiceName)/service:latest"
    }

    public func registryAuthCommands(targetConfig: AIBDeployTargetConfig) -> [DeployCommand] {
        let host = targetConfig.providerConfig["artifactRegistryHost"]
            ?? "\(targetConfig.region)-docker.pkg.dev"
        let hostForShell = shellQuote(host)
        let script = """
        set -euo pipefail
        if ! command -v docker >/dev/null 2>&1; then
          echo "docker CLI is not installed. Install Docker Desktop or OrbStack."
          exit 127
        fi
        if ! command -v gcloud >/dev/null 2>&1; then
          echo "gcloud CLI is not installed."
          exit 127
        fi
        if ! docker buildx version >/dev/null 2>&1; then
          echo "docker buildx is not available. Install Docker 23+ or enable the buildx plugin."
          exit 127
        fi
        access_token="$(gcloud auth print-access-token)"
        if [ -z "$access_token" ]; then
          echo "Failed to get gcloud access token. Run: gcloud auth login"
          exit 1
        fi
        if [ -f "$HOME/.docker/config.json" ] \\
          && ! grep -Eq "\\"\(host)\\"[[:space:]]*:[[:space:]]*\\"gcloud\\"" "$HOME/.docker/config.json"; then
          echo "Note: \(host) may not be registered with the gcloud credential helper."
          echo "If push fails with 'no basic auth credentials', run: gcloud auth configure-docker \(hostForShell)"
        fi
        echo "Registry auth validated for \(host) (docker credHelpers + gcloud)"
        """
        return [
            DeployCommand(
                label: "Validating registry authentication for Artifact Registry",
                arguments: ["bash", "-lc", script],
                stepID: AIBDeployStep.dockerAuth.rawValue
            ),
        ]
    }

    public func buildBackendPreparationCommands(targetConfig: AIBDeployTargetConfig) -> [DeployCommand] {
        // Config key kept under the legacy "appleContainer" name for backward compatibility,
        // but the disk-space threshold now triggers docker buildx / image prune instead of
        // the apple/container prune that used to live here.
        let minFreeGiB = max(1, Int(targetConfig.providerConfig["appleContainerMinFreeGiB"] ?? "") ?? 10)
        let minFreeKiB = minFreeGiB * 1024 * 1024
        let script = """
        set -euo pipefail
        if ! command -v docker >/dev/null 2>&1; then
          echo "docker CLI is not installed. Install Docker Desktop or OrbStack."
          exit 127
        fi
        if ! docker buildx version >/dev/null 2>&1; then
          echo "docker buildx is not available. Install Docker 23+ or enable the buildx plugin."
          exit 127
        fi
        if ! docker info >/dev/null 2>&1; then
          echo "docker daemon is not reachable. Start Docker Desktop or OrbStack and retry."
          exit 1
        fi

        # Materialize the active buildx builder so the build step doesn't pay the cold-start
        # latency. Idempotent — bootstrap is a no-op for an already-running builder.
        set +e
        bootstrap_output="$(docker buildx inspect --bootstrap 2>&1)"
        bootstrap_status=$?
        set -e
        if [ "$bootstrap_status" -ne 0 ]; then
          echo "$bootstrap_output"
          echo "docker buildx failed to bootstrap a builder."
          exit 1
        fi

        disk_target="/System/Volumes/Data"
        if [ ! -d "$disk_target" ]; then
          disk_target="/"
        fi

        free_kb="$(df -Pk "$disk_target" | awk 'NR==2 {print $4}')"
        case "$free_kb" in
          ''|*[!0-9]*)
            echo "Unable to determine free disk space for $disk_target; skipping cleanup."
            exit 0
            ;;
        esac

        threshold_kb=\(minFreeKiB)
        threshold_gib=\(minFreeGiB)
        free_gib="$((free_kb / 1024 / 1024))"
        echo "Free disk before build prep: ${free_gib}GiB (threshold: ${threshold_gib}GiB)"

        if [ "$free_kb" -gt "$threshold_kb" ]; then
          echo "Disk space is sufficient. Skipping docker cleanup."
          exit 0
        fi

        echo "Low disk space detected. Pruning buildx cache and unused docker images..."
        set +e
        buildx_prune_output="$(docker buildx prune -af 2>&1)"
        buildx_prune_status=$?
        set -e
        if [ -n "$buildx_prune_output" ]; then
          echo "$buildx_prune_output"
        fi
        if [ "$buildx_prune_status" -ne 0 ]; then
          echo "docker buildx prune failed while recovering disk space."
          exit 1
        fi

        set +e
        image_prune_output="$(docker image prune -af 2>&1)"
        image_prune_status=$?
        set -e
        if [ -n "$image_prune_output" ]; then
          echo "$image_prune_output"
        fi
        if [ "$image_prune_status" -ne 0 ]; then
          echo "docker image prune failed while recovering disk space."
          exit 1
        fi

        free_kb_after="$(df -Pk "$disk_target" | awk 'NR==2 {print $4}')"
        case "$free_kb_after" in
          ''|*[!0-9]*)
            echo "Cleanup completed, but failed to re-check free disk space."
            exit 0
            ;;
        esac
        free_gib_after="$((free_kb_after / 1024 / 1024))"
        echo "Free disk after build prep: ${free_gib_after}GiB"

        if [ "$free_kb_after" -lt "$threshold_kb" ]; then
          echo "Disk space is still below ${threshold_gib}GiB after cleanup. Free more disk and retry."
          exit 1
        fi
        """
        return [
            DeployCommand(
                label: "Preparing docker buildx environment",
                arguments: ["bash", "-lc", script],
                stepID: AIBDeployStep.dockerBuild.rawValue
            ),
        ]
    }

    public func ensureRegistryRepoCommands(
        service: AIBDeployServicePlan,
        targetConfig: AIBDeployTargetConfig
    ) -> [DeployCommand] {
        let gcpProject = requiredGCPProject(from: targetConfig)
        let repoName = service.deployedServiceName
        let describeCommand = [
            "gcloud", "artifacts", "repositories", "describe",
            repoName,
            "--location=\(targetConfig.region)",
            "--project=\(gcpProject)",
            "--format='value(name)'",
        ].joined(separator: " ")
        let createCommand = [
            "gcloud", "artifacts", "repositories", "create",
            repoName,
            "--repository-format=docker",
            "--location=\(targetConfig.region)",
            "--project=\(gcpProject)",
            "--quiet",
        ].joined(separator: " ")
        let script = """
        set -euo pipefail
        if \(describeCommand) >/dev/null 2>&1; then
          echo "Repository [\(repoName)] already exists."
        else
          \(createCommand)
        fi
        """
        return [
            DeployCommand(
                label: "Ensuring Artifact Registry repository for \(service.deployedServiceName)",
                arguments: ["bash", "-lc", script],
                stepID: AIBDeployStep.registrySetup.rawValue
            ),
        ]
    }

    // MARK: - Build & Push Commands

    public func buildAndPushCommands(
        imageTag: String,
        dockerfilePath: String,
        buildContext: String,
        targetConfig: AIBDeployTargetConfig
    ) -> [DeployCommand] {
        let stagedContextEnabled = parseTruthyBool(targetConfig.providerConfig["appleContainerStageContext"])
        let dockerfileArgument: String
        if dockerfilePath.hasPrefix(buildContext + "/") {
            dockerfileArgument = String(dockerfilePath.dropFirst(buildContext.count + 1))
        } else {
            dockerfileArgument = dockerfilePath
        }
        let contextForShell = shellQuote(buildContext)
        let dockerfileForShell = shellQuote(dockerfileArgument)
        let imageForShell = shellQuote(imageTag)
        let imageHost = imageTag.split(separator: "/", maxSplits: 1).first.map(String.init) ?? imageTag
        let imageHostForShell = shellQuote(imageHost)
        let script = """
        set -euo pipefail
        if ! command -v docker >/dev/null 2>&1; then
          echo "docker CLI is not installed. Install Docker Desktop or OrbStack."
          exit 127
        fi
        if ! command -v gcloud >/dev/null 2>&1; then
          echo "gcloud CLI is not installed."
          exit 127
        fi
        if ! docker buildx version >/dev/null 2>&1; then
          echo "docker buildx is not available. Install Docker 23+ or enable the buildx plugin."
          exit 127
        fi
        # docker-credential-gcloud resolves registry credentials by invoking
        # `gcloud auth print-access-token` per request. Validate that path is healthy
        # before kicking off a long build so failures surface early.
        if ! gcloud auth print-access-token >/dev/null 2>&1; then
          echo "Failed to obtain gcloud access token. Run: gcloud auth login"
          exit 1
        fi
        if [ -f "$HOME/.docker/config.json" ] \\
          && ! grep -Eq "\\"\(imageHost)\\"[[:space:]]*:[[:space:]]*\\"gcloud\\"" "$HOME/.docker/config.json"; then
          echo "Registry \(imageHost) is not registered with the gcloud credential helper."
          echo "Run: gcloud auth configure-docker \(imageHostForShell)"
          exit 1
        fi
        echo "Build backend: docker-buildx (push target \(imageHost))"
        build_start="$(date +%s)"
        cd \(contextForShell)
        stage_context="."
        stage_dir=""
        cleanup_staged_context() {
          if [ -n "${stage_dir:-}" ] && [ -d "$stage_dir" ]; then
            rm -rf "$stage_dir"
            stage_dir=""
          fi
        }
        # docker buildx applies .dockerignore on the client before streaming the
        # context, so the rsync stage below is primarily a hedge for very large
        # contexts where the streaming overhead is meaningful. Kept behind the
        # legacy `appleContainerStageContext` flag for backward compatibility.
        if [ "\(stagedContextEnabled ? "1" : "0")" = "1" ] && [ -f .dockerignore ]; then
          if grep -Eq '^[[:space:]]*!' .dockerignore; then
            echo ".dockerignore contains negation patterns; skipping staged build context optimization."
          elif command -v rsync >/dev/null 2>&1; then
            stage_sync_start="$(date +%s)"
            stage_dir="$(mktemp -d -t aib-buildx-context.XXXXXX)"
            set +e
            rsync -a --delete --exclude-from=.dockerignore ./ "$stage_dir"/
            stage_sync_status=$?
            set -e
            if [ "$stage_sync_status" -eq 0 ]; then
              stage_context="$stage_dir"
              stage_sync_end="$(date +%s)"
              echo "Prepared staged build context in $((stage_sync_end - stage_sync_start))s"
            else
              echo "Failed to stage build context with rsync (exit $stage_sync_status). Falling back to direct build context."
              cleanup_staged_context
            fi
          else
            echo "rsync not found; skipping staged build context optimization."
          fi
        fi
        build_log="$(mktemp -t aib-buildx-build.XXXXXX)"
        build_attempt=1
        build_max_attempts=2
        staged_context_fallback_attempted=0
        while true; do
          set +e
          docker buildx build \\
            --platform linux/amd64 \\
            --file \(dockerfileForShell) \\
            --tag \(imageForShell) \\
            --push \\
            "$stage_context" 2>&1 | tee "$build_log"
          build_status=${PIPESTATUS[0]}
          set -e
          if [ "$build_status" -eq 0 ]; then
            break
          fi

          if [ "$stage_context" != "." ] && [ "$staged_context_fallback_attempted" -eq 0 ]; then
            echo "Staged build context may be incompatible with this service. Retrying with direct build context..."
            cleanup_staged_context
            stage_context="."
            staged_context_fallback_attempted=1
            continue
          fi

          if grep -Eqi "ECONNRESET|npm error network aborted|connection reset by peer|TLS handshake timeout|i/o timeout|temporary failure|timeout" "$build_log" \
            && [ "$build_attempt" -lt "$build_max_attempts" ]; then
            retry_delay=$((build_attempt * 5))
            next_attempt=$((build_attempt + 1))
            echo "Transient network failure detected during image build/push. Retrying in ${retry_delay}s (attempt ${next_attempt}/${build_max_attempts})..."
            sleep "$retry_delay"
            build_attempt="$next_attempt"
            continue
          fi

          rm -f "$build_log"
          cleanup_staged_context
          exit "$build_status"
        done
        rm -f "$build_log"
        build_end="$(date +%s)"
        echo "docker buildx build+push duration: $((build_end - build_start))s"
        cleanup_staged_context
        """

        return [
            DeployCommand(
                label: "Building and pushing image",
                arguments: ["bash", "-lc", script],
                stepID: AIBDeployStep.dockerBuild.rawValue
            ),
            DeployCommand(
                label: "Image push completed",
                arguments: ["bash", "-lc", "echo \"Image pushed \(imageTag)\""],
                stepID: AIBDeployStep.dockerPush.rawValue
            ),
        ]
    }

    // MARK: - Deploy Commands

    public func deployCommands(
        service: AIBDeployServicePlan,
        imageTag: String,
        targetConfig: AIBDeployTargetConfig,
        secrets: [String: String] = [:]
    ) -> [DeployCommand] {
        let gcpProject = requiredGCPProject(from: targetConfig)

        var args = [
            "gcloud", "run", "deploy", service.deployedServiceName,
            "--image", imageTag,
            "--region", service.region,
            "--memory", service.resourceConfig.memory,
            "--cpu", service.resourceConfig.cpu,
            "--max-instances", String(service.resourceConfig.maxInstances),
            "--concurrency", String(service.resourceConfig.concurrency),
            "--timeout", service.resourceConfig.timeout,
            "--project", gcpProject,
            "--format", "value(status.url)",
            "--quiet",
        ]

        if service.isPublic {
            args.append("--allow-unauthenticated")
        } else {
            args.append("--no-allow-unauthenticated")
        }

        // Merge regular env vars + user-provided secret values and apply with
        // --set-env-vars so the Cloud Run env is replaced authoritatively.
        // --update-env-vars only merges, which would leave previously-set keys
        // (e.g. a leaked FIRESTORE_EMULATOR_HOST) on the service after they are
        // removed from workspace.yaml. Use gcloud's ^||^ custom delimiter so
        // values containing commas don't break the parser.
        //
        // Declared SecretRefs are mounted via --set-secrets (separate Cloud
        // Run mechanism); strip any collision out of the env-var dict so
        // gcloud doesn't reject the deploy with a duplicate-key error.
        let declaredSecretKeys = Set(service.declaredSecretRefs.keys)
        var allEnvVars = service.envVars.filter {
            !reservedCloudRunEnvKeys.contains($0.key) && !declaredSecretKeys.contains($0.key)
        }
        for (key, value) in secrets where !declaredSecretKeys.contains(key) {
            allEnvVars[key] = value
        }

        if allEnvVars.isEmpty {
            args.append("--clear-env-vars")
        } else {
            let delimiter = "||"
            let envString = "^" + delimiter + "^"
                + allEnvVars
                .sorted(by: { $0.key < $1.key })
                .map { "\($0.key)=\($0.value)" }
                .joined(separator: delimiter)
            args.append(contentsOf: ["--set-env-vars", envString])
        }

        // Mount declared SecretRefs from Secret Manager. Authoritative like
        // --set-env-vars: when the workspace declares no secrets, --clear-secrets
        // must run so previously-mounted entries are removed from the service.
        let secretArgs = setSecretsArgs(
            declaredSecretRefs: service.declaredSecretRefs,
            targetConfig: targetConfig
        )
        if secretArgs.isEmpty {
            args.append("--clear-secrets")
        } else {
            args.append(contentsOf: secretArgs)
        }

        return [
            DeployCommand(
                label: "Deploying to Cloud Run",
                arguments: args,
                stepID: AIBDeployStep.serviceDeploy.rawValue
            ),
        ]
    }

    // MARK: - Auth Binding Commands

    public func authBindingCommands(
        binding: AIBDeployAuthBinding,
        targetConfig: AIBDeployTargetConfig
    ) -> [DeployCommand] {
        let gcpProject = requiredGCPProject(from: targetConfig)
        let sourceForShell = shellQuote(binding.sourceServiceName)
        let targetForShell = shellQuote(binding.targetServiceName)
        let roleForShell = shellQuote(binding.role)
        let regionForShell = shellQuote(targetConfig.region)
        let projectForShell = shellQuote(gcpProject)
        let script = """
        set -euo pipefail
        source_service=\(sourceForShell)
        target_service=\(targetForShell)
        role=\(roleForShell)
        region=\(regionForShell)
        project=\(projectForShell)

        source_sa="$(gcloud run services describe "$source_service" --region "$region" --project "$project" --format='value(spec.template.spec.serviceAccountName)' 2>/dev/null | tr -d '[:space:]')"
        if [ -z "$source_sa" ]; then
          project_number="$(gcloud projects describe "$project" --format='value(projectNumber)' | tr -d '[:space:]')"
          if [ -z "$project_number" ]; then
            echo "Failed to resolve project number for $project."
            exit 1
          fi
          source_sa="${project_number}-compute@developer.gserviceaccount.com"
        fi

        if [ "${source_sa#*@}" = "$source_sa" ]; then
          source_sa="${source_sa}@${project}.iam.gserviceaccount.com"
        fi

        if ! gcloud iam service-accounts describe "$source_sa" --project "$project" >/dev/null 2>&1; then
          echo "Service account $source_sa does not exist."
          exit 1
        fi

        member="serviceAccount:${source_sa}"
        echo "Using invoker principal: ${member}"

        gcloud run services add-iam-policy-binding "$target_service" \
          --member "$member" \
          --role "$role" \
          --region "$region" \
          --project "$project" \
          --quiet
        """

        return [
            DeployCommand(
                label: "Binding IAM: \(binding.sourceServiceName) → \(binding.targetServiceName)",
                arguments: ["bash", "-lc", script],
                stepID: AIBDeployStep.authBind.rawValue
            ),
        ]
    }

    // MARK: - Existing Service URL

    public func existingServiceURL(
        serviceName: String,
        targetConfig: AIBDeployTargetConfig
    ) async -> String? {
        let gcpProject = targetConfig.providerConfig["gcpProject"] ?? ""
        guard !gcpProject.isEmpty else { return nil }

        let command = "gcloud run services describe \(serviceName)"
            + " --region=\(targetConfig.region)"
            + " --project=\(gcpProject)"
            + " --format='value(status.url)'"

        do {
            let result = try await ShellProbe.run(command: command, timeout: .seconds(15))
            guard result.exitCode == 0 else { return nil }
            let url = result.stdout.trimmingCharacters(in: .whitespacesAndNewlines)
            return url.isEmpty ? nil : url
        } catch {
            return nil
        }
    }

    // MARK: - Existing Env Vars

    public func existingEnvVarNames(
        serviceName: String,
        targetConfig: AIBDeployTargetConfig
    ) async -> Set<String> {
        let pairs = await existingEnvVars(serviceName: serviceName, targetConfig: targetConfig)
        return Set(pairs.keys)
    }

    public func existingEnvVars(
        serviceName: String,
        targetConfig: AIBDeployTargetConfig
    ) async -> [String: String] {
        let gcpProject = targetConfig.providerConfig["gcpProject"] ?? ""
        guard !gcpProject.isEmpty else { return [:] }

        // Use JSON output for reliable parsing
        let command = "gcloud run services describe \(serviceName)"
            + " --region=\(targetConfig.region)"
            + " --project=\(gcpProject)"
            + " --format='json(spec.template.spec.containers[0].env)'"

        do {
            let result = try await ShellProbe.run(command: command, timeout: .seconds(15))
            guard result.exitCode == 0, !result.stdout.isEmpty else { return [:] }

            guard let data = result.stdout.data(using: .utf8) else { return [:] }
            let jsonObject: Any
            do {
                jsonObject = try JSONSerialization.jsonObject(with: data)
            } catch {
                return [:]
            }

            let envEntries: [[String: Any]]
            if let topLevelArray = jsonObject as? [[String: Any]] {
                // `--format='json(spec.template.spec.containers[0].env)'` returns an array.
                envEntries = topLevelArray
            } else if let topLevelDict = jsonObject as? [String: Any],
                      let envArray = Self.extractEnvArray(from: topLevelDict)
            {
                // Fallback for full-service JSON output shape.
                envEntries = envArray
            } else {
                return [:]
            }

            // Cloud Run env entries come in two shapes:
            //   { "name": "FOO", "value": "bar" }                 -- plain
            //   { "name": "FOO", "valueFrom": { "secretKeyRef": ... } } -- mounted secret
            // Plain values are what we want to carry forward to avoid wiping on
            // authoritative --set-env-vars; mounted secrets are managed via
            // --set-secrets / --clear-secrets and must NOT be returned here, or
            // they would be re-set as plain env vars on the next deploy.
            var pairs: [String: String] = [:]
            for entry in envEntries {
                guard let name = entry["name"] as? String, !name.isEmpty else { continue }
                if let value = entry["value"] as? String {
                    pairs[name] = value
                }
            }
            return pairs
        } catch {
            return [:]
        }
    }

    // MARK: - Secrets (Secret Manager)

    public func setSecretsArgs(
        declaredSecretRefs: [String: SecretRef],
        targetConfig: AIBDeployTargetConfig
    ) -> [String] {
        guard !declaredSecretRefs.isEmpty else { return [] }
        // Cloud Run accepts `--set-secrets KEY=secret:version[,KEY=...]`. Sort
        // entries so the rendered command is stable across plan generations.
        let entries = declaredSecretRefs
            .sorted { $0.key < $1.key }
            .map { key, ref in "\(key)=\(ref.secret):\(ref.resolvedVersion)" }
            .joined(separator: ",")
        return ["--set-secrets", entries]
    }

    public func upsertSecret(
        name: String,
        value: String,
        targetConfig: AIBDeployTargetConfig
    ) async throws {
        let gcpProject = requiredGCPProject(from: targetConfig)
        let nameForShell = shellQuote(name)
        let projectForShell = shellQuote(gcpProject)
        // Pipe the value through stdin to avoid leaking it to argv / process
        // listings. `secrets create` returns ALREADY_EXISTS when the secret
        // already exists; in that case we skip creation and just add a version.
        let script = """
        set -euo pipefail
        if ! gcloud secrets describe \(nameForShell) --project \(projectForShell) >/dev/null 2>&1; then
          gcloud secrets create \(nameForShell) \\
            --replication-policy=automatic \\
            --project \(projectForShell) \\
            --quiet
        fi
        gcloud secrets versions add \(nameForShell) \\
          --data-file=- \\
          --project \(projectForShell) \\
          --quiet
        """

        let result: ShellProbe.Result
        do {
            result = try await ShellProbe.run(
                command: script,
                stdin: value,
                timeout: .seconds(60)
            )
        } catch {
            throw AIBDeployError(
                phase: "secrets",
                message: "Failed to upload secret '\(name)': \(error.localizedDescription)"
            )
        }

        guard result.exitCode == 0 else {
            throw AIBDeployError(
                phase: "secrets",
                message: "gcloud secrets versions add for '\(name)' exited with status \(result.exitCode). \(result.stderr)"
            )
        }
    }

    public func listSecrets(
        targetConfig: AIBDeployTargetConfig
    ) async throws -> Set<String> {
        let gcpProject = requiredGCPProject(from: targetConfig)
        let command = "gcloud secrets list"
            + " --project=\(gcpProject)"
            + " --format='value(name)'"
            + " --quiet"

        let result: ShellProbe.Result
        do {
            result = try await ShellProbe.run(command: command, timeout: .seconds(60))
        } catch {
            throw AIBDeployError(
                phase: "secrets",
                message: "Failed to list Secret Manager secrets: \(error.localizedDescription)"
            )
        }

        guard result.exitCode == 0 else {
            throw AIBDeployError(
                phase: "secrets",
                message: "gcloud secrets list exited with status \(result.exitCode). \(result.stderr)"
            )
        }

        let names = result.stdout
            .split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        return Set(names)
    }

    public func validateSecretAccess(
        name: String,
        runtimeServiceAccount: String,
        targetConfig: AIBDeployTargetConfig
    ) async throws -> Bool {
        let gcpProject = requiredGCPProject(from: targetConfig)
        // `secrets get-iam-policy` returns the policy as JSON. The accessor role
        // is `roles/secretmanager.secretAccessor`; we look for a binding with
        // that role and `serviceAccount:<sa>` in members.
        let command = "gcloud secrets get-iam-policy \(shellQuote(name))"
            + " --project=\(shellQuote(gcpProject))"
            + " --format=json"

        let result: ShellProbe.Result
        do {
            result = try await ShellProbe.run(command: command, timeout: .seconds(30))
        } catch {
            throw AIBDeployError(
                phase: "secrets",
                message: "Failed to read IAM policy for secret '\(name)': \(error.localizedDescription)"
            )
        }

        guard result.exitCode == 0 else {
            throw AIBDeployError(
                phase: "secrets",
                message: "gcloud secrets get-iam-policy exited with status \(result.exitCode). \(result.stderr)"
            )
        }

        guard let data = result.stdout.data(using: .utf8),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let bindings = json["bindings"] as? [[String: Any]] else {
            return false
        }

        let member = "serviceAccount:\(runtimeServiceAccount)"
        for binding in bindings {
            guard let role = binding["role"] as? String,
                  role == "roles/secretmanager.secretAccessor",
                  let members = binding["members"] as? [String] else { continue }
            if members.contains(member) {
                return true
            }
        }
        return false
    }

    public func grantSecretAccess(
        name: String,
        runtimeServiceAccount: String,
        targetConfig: AIBDeployTargetConfig
    ) async throws {
        let gcpProject = requiredGCPProject(from: targetConfig)
        let command = "gcloud secrets add-iam-policy-binding \(shellQuote(name))"
            + " --member=serviceAccount:\(shellQuote(runtimeServiceAccount))"
            + " --role=roles/secretmanager.secretAccessor"
            + " --project=\(shellQuote(gcpProject))"
            + " --quiet"

        let result: ShellProbe.Result
        do {
            result = try await ShellProbe.run(command: command, timeout: .seconds(60))
        } catch {
            throw AIBDeployError(
                phase: "secrets",
                message: "Failed to grant access on '\(name)' to '\(runtimeServiceAccount)': \(error.localizedDescription)"
            )
        }

        guard result.exitCode == 0 else {
            throw AIBDeployError(
                phase: "secrets",
                message: "gcloud secrets add-iam-policy-binding exited with status \(result.exitCode). \(result.stderr)"
            )
        }
    }

    // MARK: - List / Delete Deployed Services

    public func listDeployedServices(
        targetConfig: AIBDeployTargetConfig
    ) async throws -> [DeployedServiceInfo] {
        let gcpProject = requiredGCPProject(from: targetConfig)

        // List services across all regions so the UI can show drift (e.g., us-central1
        // leftovers when the workspace targets asia-northeast1).
        let command = "gcloud run services list"
            + " --project=\(gcpProject)"
            + " --format=json"
            + " --quiet"

        print("[Deployments] gcloud command: \(command)")

        let result: ShellProbe.Result
        do {
            result = try await ShellProbe.run(command: command, timeout: .seconds(60))
        } catch {
            print("[Deployments] gcloud run services list threw: \(error.localizedDescription)")
            throw AIBDeployError(
                phase: "deployments",
                message: "Failed to list Cloud Run services: \(error.localizedDescription)"
            )
        }

        print("[Deployments] gcloud exit=\(result.exitCode) stdoutBytes=\(result.stdout.count) stderrBytes=\(result.stderr.count)")
        if !result.stderr.isEmpty {
            print("[Deployments] gcloud stderr: \(result.stderr.prefix(500))")
        }

        guard result.exitCode == 0 else {
            throw AIBDeployError(
                phase: "deployments",
                message: "gcloud run services list exited with status \(result.exitCode). \(result.stderr)"
            )
        }

        guard !result.stdout.isEmpty,
              let data = result.stdout.data(using: .utf8) else {
            print("[Deployments] gcloud stdout empty — returning []")
            return []
        }

        let parsed: Any
        do {
            parsed = try JSONSerialization.jsonObject(with: data)
        } catch {
            throw AIBDeployError(
                phase: "deployments",
                message: "Failed to parse Cloud Run services list JSON: \(error.localizedDescription)"
            )
        }

        guard let array = parsed as? [[String: Any]] else {
            print("[Deployments] gcloud JSON not a top-level array — returning []")
            return []
        }
        let services = array.compactMap { Self.parseService(from: $0) }
        print("[Deployments] gcloud JSON parsed: rawEntries=\(array.count) parsedServices=\(services.count)")
        return services
    }

    public func deleteDeployedService(
        serviceName: String,
        region: String,
        targetConfig: AIBDeployTargetConfig
    ) async throws {
        let gcpProject = requiredGCPProject(from: targetConfig)

        let nameForShell = shellQuote(serviceName)
        let regionForShell = shellQuote(region)
        let projectForShell = shellQuote(gcpProject)
        let script = """
        set -euo pipefail
        if ! gcloud run services describe \(nameForShell) --region \(regionForShell) --project \(projectForShell) >/dev/null 2>&1; then
          echo "Service \(serviceName) does not exist in \(region); nothing to delete."
          exit 0
        fi
        gcloud run services delete \(nameForShell) --region \(regionForShell) --project \(projectForShell) --quiet
        """

        let result: ShellProbe.Result
        do {
            result = try await ShellProbe.run(command: script, timeout: .seconds(120))
        } catch {
            throw AIBDeployError(
                phase: "deployments",
                message: "Failed to delete \(serviceName) in \(region): \(error.localizedDescription)"
            )
        }

        guard result.exitCode == 0 else {
            throw AIBDeployError(
                phase: "deployments",
                message: "gcloud run services delete exited with status \(result.exitCode). \(result.stderr)"
            )
        }
    }

    // MARK: - Service Logs

    public func fetchServiceLogs(
        serviceName: String,
        region: String,
        limit: Int,
        targetConfig: AIBDeployTargetConfig
    ) async throws -> [CloudLogEntry] {
        let gcpProject = requiredGCPProject(from: targetConfig)
        let filter = Self.cloudRunLogFilter(serviceName: serviceName, region: region)
        let cappedLimit = max(1, min(limit, 1000))

        let command = "gcloud logging read"
            + " \(shellQuote(filter))"
            + " --project=\(shellQuote(gcpProject))"
            + " --order=desc"
            + " --limit=\(cappedLimit)"
            + " --format=json"
            + " --quiet"

        let result: ShellProbe.Result
        do {
            result = try await ShellProbe.run(command: command, timeout: .seconds(60))
        } catch {
            throw AIBDeployError(
                phase: "logs",
                message: "Failed to fetch logs for \(serviceName) in \(region): \(error.localizedDescription)"
            )
        }

        guard result.exitCode == 0 else {
            throw AIBDeployError(
                phase: "logs",
                message: "gcloud logging read exited with status \(result.exitCode). \(result.stderr)"
            )
        }

        guard !result.stdout.isEmpty,
              let data = result.stdout.data(using: .utf8) else {
            return []
        }

        let parsed: Any
        do {
            parsed = try JSONSerialization.jsonObject(with: data)
        } catch {
            throw AIBDeployError(
                phase: "logs",
                message: "Failed to parse Cloud Logging JSON: \(error.localizedDescription)"
            )
        }

        guard let array = parsed as? [[String: Any]] else { return [] }
        // gcloud logging read returns newest-first when --order=desc; the UI also expects
        // newest-first, so keep the order as-is.
        return array.compactMap { Self.parseLogEntry(from: $0) }
    }

    public func tailServiceLogs(
        serviceName: String,
        region: String,
        targetConfig: AIBDeployTargetConfig
    ) -> AsyncThrowingStream<CloudLogEntry, any Error> {
        let gcpProject = requiredGCPProject(from: targetConfig)
        let filter = Self.cloudRunLogFilter(serviceName: serviceName, region: region)
        return AsyncThrowingStream { continuation in

            // PYTHONUNBUFFERED forces gcloud (a Python tool) to flush stdout per write,
            // so the consumer sees lines as they arrive rather than in 4 KB chunks.
            let command = "PYTHONUNBUFFERED=1 gcloud beta logging tail"
                + " \(shellQuote(filter))"
                + " --project=\(shellQuote(gcpProject))"
                + " --format=json"

            let task = Task {
                do {
                    for try await line in ShellProbe.streamLines(command: command) {
                        let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
                        guard !trimmed.isEmpty,
                              let data = trimmed.data(using: .utf8) else { continue }

                        let parsed: Any
                        do {
                            parsed = try JSONSerialization.jsonObject(with: data)
                        } catch {
                            // gcloud emits informational lines on stdout occasionally
                            // (e.g. "Tailing logs..."). Skip non-JSON lines.
                            continue
                        }

                        if let object = parsed as? [String: Any],
                           let entry = Self.parseLogEntry(from: object) {
                            continuation.yield(entry)
                        }
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }

            continuation.onTermination = { _ in
                task.cancel()
            }
        }
    }

    /// Build the Cloud Logging filter that scopes results to one Cloud Run service in one region.
    static func cloudRunLogFilter(serviceName: String, region: String) -> String {
        return "resource.type=\"cloud_run_revision\""
            + " AND resource.labels.service_name=\"\(serviceName)\""
            + " AND resource.labels.location=\"\(region)\""
    }

    /// Parse a single Cloud Logging JSON entry into a `CloudLogEntry`.
    /// Returns nil only when the entry has no parseable timestamp — every other field
    /// has a sensible fallback so the row still renders.
    static func parseLogEntry(from json: [String: Any]) -> CloudLogEntry? {
        guard let timestampRaw = json["timestamp"] as? String,
              let date = Self.parseLogTimestamp(timestampRaw) else {
            return nil
        }

        let severity = (json["severity"] as? String).flatMap { $0.isEmpty ? nil : $0 } ?? "DEFAULT"

        let resource = json["resource"] as? [String: Any]
        let labels = resource?["labels"] as? [String: Any]
        let revision = (labels?["revision_name"] as? String).flatMap { $0.isEmpty ? nil : $0 }

        let message = Self.extractMessage(from: json)

        return CloudLogEntry(
            timestamp: date,
            severity: severity,
            revisionName: revision,
            message: message
        )
    }

    private static func extractMessage(from json: [String: Any]) -> String {
        if let text = json["textPayload"] as? String, !text.isEmpty {
            return text
        }

        if let payload = json["jsonPayload"] as? [String: Any] {
            if let msg = payload["message"] as? String, !msg.isEmpty {
                return msg
            }
            if let err = (payload["error"] as? [String: Any])?["message"] as? String, !err.isEmpty {
                return err
            }
            return Self.serializeJSON(payload) ?? "(structured payload)"
        }

        if let proto = json["protoPayload"] as? [String: Any] {
            if let methodName = proto["methodName"] as? String, !methodName.isEmpty {
                return methodName
            }
            return Self.serializeJSON(proto) ?? "(proto payload)"
        }

        if let httpRequest = json["httpRequest"] as? [String: Any] {
            let method = httpRequest["requestMethod"] as? String ?? "?"
            let url = httpRequest["requestUrl"] as? String ?? ""
            let status = httpRequest["status"] as? Int ?? 0
            return "\(method) \(url) → \(status)"
        }

        return "(no payload)"
    }

    private static func serializeJSON(_ value: [String: Any]) -> String? {
        do {
            let data = try JSONSerialization.data(withJSONObject: value, options: [.sortedKeys])
            return String(data: data, encoding: .utf8)
        } catch {
            return nil
        }
    }

    private static func parseLogTimestamp(_ raw: String) -> Date? {
        let withFraction = ISO8601DateFormatter()
        withFraction.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        if let date = withFraction.date(from: raw) { return date }

        let plain = ISO8601DateFormatter()
        plain.formatOptions = [.withInternetDateTime]
        return plain.date(from: raw)
    }

    // MARK: - Parse Output

    public func parseDeployedURL(from output: String) -> String? {
        let trimmed = output.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        return trimmed
    }

    // MARK: - Auth Binding Member

    public func authBindingMember(
        sourceServiceName: String,
        targetConfig: AIBDeployTargetConfig
    ) -> String {
        let gcpProject = requiredGCPProject(from: targetConfig)
        return "serviceAccount:\(sourceServiceName)@\(gcpProject).iam.gserviceaccount.com"
    }

    // MARK: - Private

    /// Extract gcpProject from validated config.
    /// Precondition: `validateTargetConfig()` must have been called before any method that uses this.
    private func requiredGCPProject(from targetConfig: AIBDeployTargetConfig) -> String {
        guard let project = targetConfig.providerConfig["gcpProject"], !project.isEmpty else {
            preconditionFailure(
                "gcpProject is missing from targetConfig. "
                + "validateTargetConfig() must be called before deploy/auth operations."
            )
        }
        return project
    }

    private func shellQuote(_ value: String) -> String {
        "'\(value.replacingOccurrences(of: "'", with: "'\"'\"'"))'"
    }

    private func parseTruthyBool(_ raw: String?) -> Bool {
        guard let value = raw?.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() else {
            return false
        }
        switch value {
        case "1", "true", "yes", "on":
            return true
        default:
            return false
        }
    }

    /// Parse a single service entry from `gcloud run services list --format=json` output.
    /// Returns nil when the entry is missing the minimum identifying fields.
    static func parseService(from json: [String: Any]) -> DeployedServiceInfo? {
        let metadata = json["metadata"] as? [String: Any] ?? [:]
        let spec = json["spec"] as? [String: Any] ?? [:]
        let template = spec["template"] as? [String: Any] ?? [:]
        let templateSpec = template["spec"] as? [String: Any] ?? [:]
        let containers = templateSpec["containers"] as? [[String: Any]] ?? []
        let firstContainer = containers.first ?? [:]
        let status = json["status"] as? [String: Any] ?? [:]
        let labels = metadata["labels"] as? [String: Any] ?? [:]

        guard let name = metadata["name"] as? String, !name.isEmpty else { return nil }

        // Region is published by Cloud Run as the `cloud.googleapis.com/location` label.
        let region = (labels["cloud.googleapis.com/location"] as? String) ?? ""
        guard !region.isEmpty else { return nil }

        let url = (status["url"] as? String).flatMap { $0.isEmpty ? nil : $0 }
        let image = (firstContainer["image"] as? String).flatMap { $0.isEmpty ? nil : $0 }
        let timeoutSeconds = templateSpec["timeoutSeconds"].flatMap { value -> Int? in
            if let intVal = value as? Int { return intVal }
            if let strVal = value as? String { return Int(strVal) }
            if let dblVal = value as? Double { return Int(dblVal) }
            return nil
        }
        let envEntries = firstContainer["env"] as? [[String: Any]] ?? []
        let envVarNames: Set<String> = Set(envEntries.compactMap { $0["name"] as? String })

        let revisionName = (status["latestReadyRevisionName"] as? String)
            ?? (status["latestCreatedRevisionName"] as? String)

        let generation: Int? = {
            if let intVal = metadata["generation"] as? Int { return intVal }
            if let strVal = metadata["generation"] as? String { return Int(strVal) }
            if let dblVal = metadata["generation"] as? Double { return Int(dblVal) }
            return nil
        }()

        let lastDeployedAt: Date? = {
            // Look for the most recent condition's lastTransitionTime.
            let conditions = status["conditions"] as? [[String: Any]] ?? []
            let latestTransition = conditions
                .compactMap { $0["lastTransitionTime"] as? String }
                .compactMap(Self.parseISO8601)
                .max()
            if let latestTransition { return latestTransition }
            if let creation = metadata["creationTimestamp"] as? String,
               let parsed = Self.parseISO8601(creation) {
                return parsed
            }
            return nil
        }()

        return DeployedServiceInfo(
            name: name,
            region: region,
            url: url,
            image: image,
            lastDeployedAt: lastDeployedAt,
            revisionName: revisionName,
            generation: generation,
            timeoutSeconds: timeoutSeconds,
            envVarNames: envVarNames
        )
    }

    private static func parseISO8601(_ raw: String) -> Date? {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        if let date = formatter.date(from: raw) { return date }
        formatter.formatOptions = [.withInternetDateTime]
        return formatter.date(from: raw)
    }

    private static func extractEnvArray(from json: [String: Any]) -> [[String: Any]]? {
        if let env = json["env"] as? [[String: Any]] {
            return env
        }
        if let spec = json["spec"] as? [String: Any],
           let template = spec["template"] as? [String: Any],
           let templateSpec = template["spec"] as? [String: Any],
           let containers = templateSpec["containers"] as? [[String: Any]],
           let first = containers.first,
           let env = first["env"] as? [[String: Any]]
        {
            return env
        }
        return nil
    }

}
