import Foundation

/// GCP Cloud Run deployment provider.
/// Consolidates all Cloud Run-specific logic: preflight checks, URL resolution,
/// config generation, and deployment commands.
public struct GCPCloudRunProvider: DeploymentProvider, Sendable {

    /// Environment variable names reserved by Cloud Run (auto-set by the system).
    private static let reservedCloudRunEnvKeys: Set<String> = [
        "PORT", "K_SERVICE", "K_REVISION", "K_CONFIGURATION",
    ]
    private var reservedCloudRunEnvKeys: Set<String> { Self.reservedCloudRunEnvKeys }

    public var providerID: String { "gcp-cloudrun" }
    public var displayName: String { "Google Cloud Run" }

    public init() {}

    // MARK: - Preflight

    public func preflightCheckers() -> [any PreflightChecker] {
        [
            GCloudInstalledChecker(),
            GCloudAuthenticatedChecker(),
            GCloudProjectChecker(),
            DockerInstalledChecker(),
            DockerDaemonChecker(),
            CloudRunAPIChecker(),
        ]
    }

    public func preflightDependencies() -> [PreflightCheckID: [PreflightCheckID]] {
        [
            .gcloudInstalled: [.gcloudAuthenticated, .gcloudProjectConfigured, .cloudRunAPIEnabled],
            .dockerInstalled: [.dockerDaemonRunning],
        ]
    }

    // MARK: - Config Detection & Validation

    public func extractDetectedConfig(from report: PreflightReport) -> [String: String] {
        var detected: [String: String] = [:]
        if let project = report.detail(for: .gcloudProjectConfigured), !project.isEmpty {
            detected["gcpProject"] = project
        }
        return detected
    }

    public func validateTargetConfig(_ config: AIBDeployTargetConfig) throws {
        guard let gcpProject = config.providerConfig["gcpProject"], !gcpProject.isEmpty else {
            throw AIBDeployError(
                phase: "config",
                message: "GCP project is required. Set it in .aib/targets/gcp-cloudrun.yaml or ensure gcloud is configured."
            )
        }
    }

    // MARK: - Service Naming

    /// Sanitize a package-derived service name into a valid Cloud Run service name.
    /// Cloud Run names: lowercase letters, hyphens, max 63 chars.
    /// Example: "MyService" -> "myservice"
    public func deployedServiceName(from namespacedID: String) -> String {
        let sanitized = namespacedID
            .replacingOccurrences(of: "/", with: "-")
            .lowercased()
            .filter { $0.isLetter || $0.isNumber || $0 == "-" }

        let trimmed: String
        if let first = sanitized.first, first.isLetter {
            trimmed = sanitized
        } else {
            trimmed = "svc-" + sanitized
        }

        return String(trimmed.prefix(63))
    }

    // MARK: - URL Resolution

    /// Resolve a service_ref to a Cloud Run URL.
    /// At plan time the exact hash is unknown, so we use the deterministic form.
    public func resolveURL(
        serviceRef: String,
        region: String,
        path: String?,
        serviceNameMap: [String: String]
    ) -> String {
        let cloudRunName = serviceNameMap[serviceRef] ?? deployedServiceName(from: serviceRef)
        let basePath = path ?? "/mcp"
        return "https://\(cloudRunName)-\(region).a.run.app\(basePath)"
    }

    // MARK: - Deploy Config Generation

    /// Generate clouddeploy.yaml content for a Cloud Run service.
    public func generateDeployConfig(service: AIBDeployServicePlan) -> String {
        var lines: [String] = []
        lines.append("# Generated by AIB — do not edit manually")
        lines.append("service: \(service.deployedServiceName)")
        lines.append("region: \(service.region)")
        lines.append("resources:")
        lines.append("  memory: \(service.resourceConfig.memory)")
        lines.append("  cpu: \(service.resourceConfig.cpu)")
        lines.append("scaling:")
        lines.append("  max_instances: \(service.resourceConfig.maxInstances)")
        lines.append("  min_instances: 0")
        lines.append("  concurrency: \(service.resourceConfig.concurrency)")
        lines.append("timeout: \(service.resourceConfig.timeout)")
        lines.append("auth: \(service.isPublic ? "public" : "private")")

        let planEnvVars = service.envVars.filter { !reservedCloudRunEnvKeys.contains($0.key) }
        if !planEnvVars.isEmpty {
            lines.append("env:")
            for (key, value) in planEnvVars.sorted(by: { $0.key < $1.key }) {
                lines.append("  \(key): \"\(value)\"")
            }
        }

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Container Registry

    public func registryImageTag(
        service: AIBDeployServicePlan,
        targetConfig: AIBDeployTargetConfig
    ) -> String {
        let gcpProject = requiredGCPProject(from: targetConfig)
        let host = targetConfig.providerConfig["artifactRegistryHost"]
            ?? "\(targetConfig.region)-docker.pkg.dev"
        return "\(host)/\(gcpProject)/\(service.deployedServiceName)/service:latest"
    }

    public func registryAuthCommands(targetConfig: AIBDeployTargetConfig) -> [DeployCommand] {
        let host = targetConfig.providerConfig["artifactRegistryHost"]
            ?? "\(targetConfig.region)-docker.pkg.dev"
        return [
            DeployCommand(
                label: "Configuring Docker authentication for Artifact Registry",
                arguments: ["gcloud", "auth", "configure-docker", host, "--quiet"],
                stepID: AIBDeployStep.dockerAuth.rawValue
            ),
        ]
    }

    public func ensureRegistryRepoCommands(
        service: AIBDeployServicePlan,
        targetConfig: AIBDeployTargetConfig
    ) -> [DeployCommand] {
        let gcpProject = requiredGCPProject(from: targetConfig)
        return [
            DeployCommand(
                label: "Ensuring Artifact Registry repository for \(service.deployedServiceName)",
                arguments: [
                    "gcloud", "artifacts", "repositories", "create",
                    service.deployedServiceName,
                    "--repository-format=docker",
                    "--location=\(targetConfig.region)",
                    "--project=\(gcpProject)",
                    "--quiet",
                ],
                stepID: AIBDeployStep.registrySetup.rawValue
            ),
        ]
    }

    // MARK: - Build & Push Commands

    public func buildAndPushCommands(
        imageTag: String,
        dockerfilePath: String,
        buildContext: String
    ) -> [DeployCommand] {
        [
            DeployCommand(
                label: "Building container image",
                arguments: [
                    "docker", "build",
                    "--platform", "linux/amd64",
                    "-t", imageTag,
                    "-f", dockerfilePath,
                    buildContext,
                ],
                stepID: AIBDeployStep.dockerBuild.rawValue
            ),
            DeployCommand(
                label: "Pushing to Artifact Registry",
                arguments: ["docker", "push", imageTag],
                stepID: AIBDeployStep.dockerPush.rawValue
            ),
        ]
    }

    // MARK: - Deploy Commands

    public func deployCommands(
        service: AIBDeployServicePlan,
        imageTag: String,
        targetConfig: AIBDeployTargetConfig,
        secrets: [String: String] = [:]
    ) -> [DeployCommand] {
        let gcpProject = requiredGCPProject(from: targetConfig)

        var args = [
            "gcloud", "run", "deploy", service.deployedServiceName,
            "--image", imageTag,
            "--region", service.region,
            "--memory", service.resourceConfig.memory,
            "--cpu", service.resourceConfig.cpu,
            "--max-instances", String(service.resourceConfig.maxInstances),
            "--concurrency", String(service.resourceConfig.concurrency),
            "--timeout", service.resourceConfig.timeout,
            "--project", gcpProject,
            "--format", "value(status.url)",
            "--quiet",
        ]

        if service.isPublic {
            args.append("--allow-unauthenticated")
        } else {
            args.append("--no-allow-unauthenticated")
        }

        // Merge regular env vars + secrets into a single --set-env-vars.
        // Use gcloud's ^||^ custom delimiter to avoid values containing commas
        // or other special characters from breaking the parser.
        var allEnvVars = service.envVars.filter { !reservedCloudRunEnvKeys.contains($0.key) }
        for (key, value) in secrets {
            allEnvVars[key] = value
        }

        if !allEnvVars.isEmpty {
            let delimiter = "||"
            let envString = "^" + delimiter + "^"
                + allEnvVars
                .sorted(by: { $0.key < $1.key })
                .map { "\($0.key)=\($0.value)" }
                .joined(separator: delimiter)
            args.append(contentsOf: ["--set-env-vars", envString])
        }

        return [
            DeployCommand(
                label: "Deploying to Cloud Run",
                arguments: args,
                stepID: AIBDeployStep.serviceDeploy.rawValue
            ),
        ]
    }

    // MARK: - Auth Binding Commands

    public func authBindingCommands(
        binding: AIBDeployAuthBinding,
        targetConfig: AIBDeployTargetConfig
    ) -> [DeployCommand] {
        let gcpProject = requiredGCPProject(from: targetConfig)

        return [
            DeployCommand(
                label: "Binding IAM: \(binding.sourceServiceName) → \(binding.targetServiceName)",
                arguments: [
                    "gcloud", "run", "services", "add-iam-policy-binding",
                    binding.targetServiceName,
                    "--member", binding.member,
                    "--role", binding.role,
                    "--region", targetConfig.region,
                    "--project", gcpProject,
                    "--quiet",
                ],
                stepID: AIBDeployStep.authBind.rawValue
            ),
        ]
    }

    // MARK: - Existing Env Vars

    public func existingEnvVarNames(
        serviceName: String,
        targetConfig: AIBDeployTargetConfig
    ) async -> Set<String> {
        let gcpProject = targetConfig.providerConfig["gcpProject"] ?? ""
        guard !gcpProject.isEmpty else { return [] }

        // Use JSON output for reliable parsing
        let command = "gcloud run services describe \(serviceName)"
            + " --region=\(targetConfig.region)"
            + " --project=\(gcpProject)"
            + " --format='json(spec.template.spec.containers[0].env)'"

        do {
            let result = try await ShellProbe.run(command: command, timeout: .seconds(15))
            guard result.exitCode == 0, !result.stdout.isEmpty else { return [] }

            // JSON output: {"spec":{"template":{"spec":{"containers":[{"env":[{"name":"KEY","value":"..."}]}]}}}}
            guard let data = result.stdout.data(using: .utf8),
                  let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
            else { return [] }

            // Navigate the nested structure
            var names: Set<String> = []
            let envArray: [[String: Any]]? = {
                if let spec = json["spec"] as? [String: Any],
                   let template = spec["template"] as? [String: Any],
                   let templateSpec = template["spec"] as? [String: Any],
                   let containers = templateSpec["containers"] as? [[String: Any]],
                   let first = containers.first,
                   let env = first["env"] as? [[String: Any]]
                {
                    return env
                }
                return nil
            }()

            if let envArray {
                for entry in envArray {
                    if let name = entry["name"] as? String {
                        names.insert(name)
                    }
                }
            }
            return names
        } catch {
            return []
        }
    }

    // MARK: - Parse Output

    public func parseDeployedURL(from output: String) -> String? {
        let trimmed = output.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        return trimmed
    }

    // MARK: - Auth Binding Member

    public func authBindingMember(
        sourceServiceName: String,
        targetConfig: AIBDeployTargetConfig
    ) -> String {
        let gcpProject = requiredGCPProject(from: targetConfig)
        return "serviceAccount:\(sourceServiceName)@\(gcpProject).iam.gserviceaccount.com"
    }

    // MARK: - Private

    /// Extract gcpProject from validated config.
    /// Precondition: `validateTargetConfig()` must have been called before any method that uses this.
    private func requiredGCPProject(from targetConfig: AIBDeployTargetConfig) -> String {
        guard let project = targetConfig.providerConfig["gcpProject"], !project.isEmpty else {
            preconditionFailure(
                "gcpProject is missing from targetConfig. "
                + "validateTargetConfig() must be called before deploy/auth operations."
            )
        }
        return project
    }
}
